name: PR CI Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18.1

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v .
