name: PR CI Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'src/go.mod'
          check-latest: true
          cache-dependency-path: |
            src/go.sum

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        working-directory: src
        run: go build

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        working-directory: src
        run: go test -v
